/* eslint no-console:0 */
'use strict';

export const SPECCER_LITERALS = [...'ABCDEFGHIJKLMNOPQRSTUVWXYZ'];

export const SPECCER_TAGS_TO_AVOID = [
  'TR',
  'TH',
  'TD',
  'TBODY',
  'THEAD',
  'TFOOT'
];

export const SPECCER_DEFAULT_PIN_SPACE = 48;

export const SPECCER_DEFAULT_PIN_SPACE_NEG = SPECCER_DEFAULT_PIN_SPACE * -1;

export const SPECCER_DEFAULT_MEASURE_SIZE = 8;

export const SPECCER_DEFAULT_MEASURE_SIZE_NEG =
  SPECCER_DEFAULT_MEASURE_SIZE * -1;

export const SPECCER_DEFAULT_LINE_WIDTH = 1;
