name: "Pull Request Labeler"
on:
- pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      issues: write
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
    - id: label-the-PR
      uses: actions/labeler@v7
      with:
        sync-labels: true
